//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Trainnig
{
    using System;
    
    public enum CourseCredits : int
    {
        Level1 = 1,
        Level2 = 2,
        Level3 = 3
    }
}
